module.exports =
{
  // 'animal': ['panda','fox','capybara','iguana'],
  
  // 'emotion': ['sad','happy','angry','jealous'],
  
  'encouraging': 
  [
    'amazing',
    'awesome',
    'beautiful',
    // 'bravo',
    'brilliant',
    'breathtaking',
    // 'congratulations',
    // 'cool',
    'dazzling',
    'delightful',
    'electrifying',
    // 'elegant',
    'enchanting',
    'excellent',
    'exciting',
    'fabulous',
    'fantastic',
    'fun',
    // 'genius',
    'groundbreaking',
    'heavenly',
    'impressive',
    // 'innovative',
    // 'inventive',
    // 'kind',
    'legendary',
    'lifechanging',
    'lovely',
    'magical',
    'marvelous',
    'masterful',
    'miraculous',
    'original',
    'perfect',
    'phenomenal',
    'powerful',
    'remarkable',
    'rejuvenating',
    'resounding',
    // 'skillful',
    'stupendous',
    'stunning',
    'sweet',
    'terrific',
    // 'thoughtful',
    'thrilling',
    'wonderful',
    'wondrous'
  ],
  
  'weather':
  [
    'clear',
    'hazy',
    'frosty',
    'dark',
    'drizzly',
    'showery',
    'tempestuous',
    'hot',
    'scorching',
    'arid',
    'damp',
    'sunny',
    'cloudy',
    'stormy',
    'dry',
    'warm',
    'steamy',
    'muggy',
    'misty',
    'icey',
    'balmy',
    'calm',
    'windy',
    'freezing',
    'rainy',
    'foggy',
    'bitter',
    'humid',
    'wet',
    'blusterous',
    'harsh',
    'sultry',
    // 'heavy',
    // 'variable',
    'thundery',
    'scattered',
    'floody',
    'unsettled',
    'torrid',
    'boiling',
    'tropical',
    'blistering',
    'chilly',
    'nippy',
    // 'cooler'
  ],
  
  'surface': 'cement stone rock asphalt tarmac macadam concrete mud sand gravel'.split(' '),
  
  'verbing': 
  [
    'Driving through ',
    'Finding myself in ',
    'Peaceful in ',
    'Wandering through ',
    'Meditating in ',
    'Exploring ',
    'Contemplating in ',
    'Hungover in ',
    'Winging it in ',
    'Bird watching in ',
    'Stumbling through ',
    'Best day in ',
    'True love in ',
    'The time is now in ',
    'Every moment is beautiful in ',
    'Loitering in ',
    'Lurking around ',
    'Lost in ',
    'Letting it all go in '
  ]
} 